language: python
sudo: required
jobs:
  include:
  - name: Python 3.9 on macOS
    os: osx
    osx_image: xcode12.5.1
    language: shell
before_install:
- python3 --version
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- sudo python3 get-pip.py
install:
- pip3 install boto3 --user
- sudo gem install fastlane
branches:
  only:
  - master
before_script:
  - chmod +x ./scripts/add-key.sh 
  - pod install
script:
  - python3 ./travis.py

