language: objective-c
jobs:
  include:
  - name: Python 3.9 on macOS
    os: osx
    osx_image: xcode11
    language: shell
env:
  global:
  - APPNAME="travis"
  - 'DEVELOPER_NAME="iPhone Distribution: Hao Zheng (F6CYAWT7QB)"'
  - PROFILE_NAME="tap_adc"
before_install:
  - chmod +x scripts/add-key.sh
  - chmod +x scripts/build.sh
  - chmod +x scripts/remove-key.sh
install:
  - sudo gem install fastlane --version "2.186.0"
branches:
  only:
  - master
# before_script:
# - "./scripts/add-key.sh"
script:
- fastlane beta_release
# after_script:
# - "./scripts/remove-key.sh"

