language: objective-c
osx_image: xcode9
env:
  global:
  - APPNAME="travis"
  - 'DEVELOPER_NAME="iPhone Distribution: Hao Zheng (F6CYAWT7QB)"'
  - PROFILE_NAME="tap_adc"
before_install:
  - chmod +x scripts/add-key.sh
  - chmod +x scripts/build.sh
  - chmod +x scripts/remove-key.sh
before_script:
- "./scripts/add-key.sh"
script:
- "./scripts/build.sh"
after_script:
- "./scripts/remove-key.sh"

