language: objective-c
# 初始化环境
jobs:
  include:
  - name: Python 3.9 on macOS
    os: osx
    osx_image: xcode12.5.1
    language: shell
# 设置相关证书
env:
  global:
    - APPNAME="travis"
    - 'DEVELOPER_NAME="iPhone Distribution: Hao Zheng (F6CYAWT7QB)"'
    - PROFILE_NAME="tapnow_adc"
before_install:
  # 安装python依赖
  - python3 --version
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  # 安装fastlane
  - gem install fastlane
  # 安装cocoapods
  - gem install cocoapods -v 1.10.1
  # 证书使用
  - chmod 777 ./add-key.sh
install:
  # 安装aws3的依赖
  - pip3 install boto3 --user
branches:
  only:
  - master
script:
  - python3 travis.py
  - chomd 777 ./remove-key.sh
