language: python
python: 
  - "3.9"
jobs:
  include:
  - name: Python 3.9 on macOS
    os: osx
    osx_image: xcode11
    language: shell
install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3 get-pip.py
  - pip3 install boto3 --user
  - sudo gem install fastlane --version "2.186.0"
  - sudo gem install cocoapods -v 1.10.1
branches:
  only:
  - master
script:
  - pod install
  - fastlane beta_release buildnumber:101 ipaname:travis.ipa

